### ISSUE TITLE
Failed build and Preview

### ISSUE THREAD

**Issue by Alex-AGD** [timofei-iatsenko/keycloakify-emails#5]
Hi,

I'm encountering an issue with building the theme using emails_preview^2.0.0 с keycloakify v11.5.0  on Windows. Here's what I've tried so far:

I followed the official tutorial and made necessary adjustments to the configuration, but I’m still facing an issue.
Currently, after configuring vite.config.ts and required dependencies, I’m getting the following error related to ESM modules:
`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
`

It seems like the problem is that Node.js on Windows expects valid file:// URLs for absolute paths, causing a failure when trying to load the module.

Additionally, when I try running emails_preview, I’m getting this error:
`ReferenceError: require is not defined
    at moduleImport (file:///C:/Projects/A1/kc-marketplace-theme/node_modules/jsx-email/src/config.ts:200:7)
    at Object.search (C:/Projects/A1/kc-marketplace-theme/node_modules/lilconfig/src/index.js:225:23)
    at loadConfig (file:///C:/Projects/A1/kc-marketplace-theme/node_modules/jsx-email/src/config.ts:218:24)
    at run (file:///C:/Projects/A1/kc-marketplace-theme/node_modules/jsx-email/src/cli/main.mts:42:3)
`

The issue seems to be related to require not being defined in the ES module context.

Could you help me understand what's going wrong here and suggest any potential fixes? I’d appreciate any guidance on how to resolve these issues.

Thanks in advance!

**Comment by timofei-iatsenko** [comment]
Hey, i haven't tested it under native Windows platform. I don't have one so it's extremly hard to me to fix the issues related to Windows. I happily will accept PR's related to this one and could guide you throw the debugging process (in a discord for example) if needed. 

I'm pretty sure that there are issues somewhere in the path handling, so it should be easy to fix. 

Regarding `emails preview` here it is used completely as-is from the upstream "jsx-emails", so it better to fill an issue in theirs repo.  I would suggest to check first what configuration in tsconfig you have, what "type" field value in the package.json and that you don't have any explicit require calls in you user's code. 

`jsx-emails` first building your templates using esbuild, and then importing it into the preview application. So if the esbuild for some reason is generating commonjs, but you have "type: module" in package.json it will not work

**Comment by Alex-AGD** [comment]
Hi,

Thank you for the detailed feedback. Based on your suggestions, here’s what I’ve checked and configured so far:

tsconfig.json: My configuration is as follows:
```
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Node",
    "target": "ES2020",
    "esModuleInterop": true
  }
}

package.json: I’m using "type": "module", and I’ve verified that there are no explicit require calls in my user code.

esbuild Configuration: I’m specifying the format: "esm" in the esbuild options for the email theme build process:


```
esbuild: {
    format: "esm"
}
```



path.resolve(__dirname, 'emails', 'templates')
However, there seems to still be an issue where file:// URLs are being misinterpreted or appended incorrectly, resulting in paths like:

C:\Projects\A1\kc-marketplace-theme\dist_keycloak\resources\file:\C:\Projects\A1\kc-marketplace-theme\emails\templates
Despite these changes, I’m still encountering the same issues related to file:// URLs and path handling on Windows.

Could this be related to how absolute paths are handled within emails_preview or the build process? I’d appreciate any further guidance on debugging or potential workarounds.


`import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";
import { buildEmailTheme } from "keycloakify-emails";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default defineConfig(async () => ({
    plugins: [
        react(),
        keycloakify({
            accountThemeImplementation: "none",
            keycloakVersionTargets: {
                "22-to-25": false,
                "all-other-versions": "market_theme.jar"
            },
            postBuild: async buildContext => {
                await buildEmailTheme({
                    templatesSrcDirPath: path.join(__dirname, "emails/templates"),
                    i18nSourceFile: path.join(__dirname, "emails/i18n.ts"),
                    themeNames: buildContext.themeNames,
                    keycloakifyBuildDirPath: buildContext.keycloakifyBuildDirPath,
                    locales: ["en", "ru"],
                    cwd: __dirname,
                    esbuild: { format: "esm" }
                });
            }
        })
    ]
}));
`
```
error when starting dev server:
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupported
```

Thanks in advance for your help!

**Comment by timofei-iatsenko** [comment]
You can use `import.meta.dirname` instead of `const __filename = fileURLToPath(import.meta.url);`

As i mentioned, the `emails preview` a command which as-is used from `jsx-email`. It's better to fill an issue on thiers repo. 
The `keycloakify-emails` does nothing here, the vite configuration is not used. Have you followed theirs [quick start guide](https://jsx.email/docs/quick-start)?  

Regarding windows path, my general recomendation - use WSL for development, you will save a lot of time for yourself. If it's not possible, please try to debug this library. The code is very short and straightforward. I will happily accept a PR with a fixes.

**Comment by Alex-AGD** [comment]
@timofei-iatsenko  Thank you for your quick response and the suggestions! I appreciate the update regarding the path handling and the new release with Windows testing. I’ll check everything tomorrow and test the changes with version 2.0.1.

Regarding import.meta.dirname, I’ll update my code accordingly and verify if it resolves the issue.

Thanks again for your help! I'll let you know if the problem persists after testing.

**Comment by timofei-iatsenko** [comment]
> Regarding import.meta.dirname, I’ll update my code accordingly and verify if it resolves the issue.

It will not resolve the issue for sure. It's just a hint for cleaner code.

**Comment by timofei-iatsenko** [comment]
I just tested this in our project and this become broken, even the tests are passing. I will take a look at this. (this may still works on the windows)

**Comment by timofei-iatsenko** [comment]
I was able to fix problems related to `keycloakify-emails` on Windows, but the upstream `jsx-email` still doesn't work properly. I added a smoke tests in this repo, and they're indeed failing with an issue you mentioned.  I raised the problem in their's repo https://github.com/shellscape/jsx-email/pull/269

Meanwhile, you can use another email js solution or use WSL to develop.

**Comment by Alex-AGD** [comment]
Thank you so much for your efforts and the detailed updates! I really appreciate the time and effort you’ve put into identifying and addressing these issues.

To simplify my development process, I’ve started using Docker, which has helped me resolve the problems related to keycloakify-emails on Windows. However, I understand that the upstream jsx-email still has some unresolved issues, and I’m grateful that you’ve raised the problem in their repository.

Thank you again for your guidance and support throughout this process. It’s clear how much effort you’re putting into making this work for everyone, and I truly appreciate it.
